/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estadoderesultado;

/**
 *
 * @author JAVIER
 */
public class Estado extends javax.swing.JFrame {

    /**
     * Creates new form Estado
     */
    public Estado() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator53 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        jSeparator54 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator55 = new javax.swing.JSeparator();
        jSeparator57 = new javax.swing.JSeparator();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        jSeparator60 = new javax.swing.JSeparator();
        VentasMer = new javax.swing.JTextField();
        IngresosFin = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        CostosFin = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        GastosVentas = new javax.swing.JTextField();
        GAstosdeAdministracion = new javax.swing.JTextField();
        OtrosGastos = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        CostosMer = new javax.swing.JTextField();
        TotalIngresos2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jSeparator46 = new javax.swing.JSeparator();
        jSeparator47 = new javax.swing.JSeparator();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jSeparator50 = new javax.swing.JSeparator();
        jSeparator51 = new javax.swing.JSeparator();
        jSeparator52 = new javax.swing.JSeparator();
        jSeparator61 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        jSeparator63 = new javax.swing.JSeparator();
        TotalIngresos1 = new javax.swing.JTextField();
        UtilidadBruta = new javax.swing.JTextField();
        TotalCostos = new javax.swing.JTextField();
        TotalGastos = new javax.swing.JTextField();
        UtilidadesdelPeriodo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ESTADO DE RESULTADO AL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 220, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE DE LA EMPRESA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 260, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 110));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("INGRESOS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 200, 30));

        jLabel5.setText("Ventas de Mercaderias");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 30));

        jLabel6.setText("Ingresos Financieros");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Total Ingresos");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("COSTOS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 30));

        jLabel10.setText("Costos de Mercaderias");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 30));

        jLabel11.setText("Costos Financieros");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Total Costos");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 30));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("UTILIDAD BRUTA");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 30));
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 200, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("GASTOS");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 30));

        jLabel17.setText("UTILIDADES DEL PERIODO");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 200, 30));

        jLabel18.setText("Otros gastos");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 80, 30));

        jLabel19.setText("Gastos de Administracion");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 40));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 40));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 40));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 40));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 40));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 40));

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 40));

        jSeparator24.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 40));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 40));

        jSeparator26.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 40));

        jSeparator25.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 270, 40));

        jSeparator28.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 230, 40));

        jSeparator29.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 240, 40));

        jSeparator27.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 220, 50));
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 200, 30));

        jLabel21.setText("Gastos de Ventas");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 160, 30));

        jSeparator31.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 40));

        jSeparator43.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 220, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Total Gastos");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 120, 30));
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 80, 30));

        jSeparator53.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 240, 40));

        jSeparator56.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 240, 40));

        jSeparator54.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 600));

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 40));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 40));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 40));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 40));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 40));

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 40));

        jSeparator32.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 170, 40));

        jSeparator33.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 170, 40));

        jSeparator35.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 70, 40));

        jSeparator36.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        jSeparator37.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 160, 40));

        jSeparator38.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 170, 40));

        jSeparator39.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 170, 40));

        jSeparator40.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 170, 40));

        jSeparator41.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 160, 40));

        jSeparator42.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 150, 40));

        jSeparator55.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, 40));

        jSeparator57.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 170, 40));

        jSeparator58.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 160, 40));

        jSeparator59.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 160, 40));

        jSeparator60.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 190, 40));

        VentasMer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VentasMer.setBorder(new javax.swing.border.MatteBorder(null));
        VentasMer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasMerActionPerformed(evt);
            }
        });
        jPanel3.add(VentasMer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 30));

        IngresosFin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IngresosFin.setBorder(new javax.swing.border.MatteBorder(null));
        IngresosFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresosFinActionPerformed(evt);
            }
        });
        jPanel3.add(IngresosFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        jTextField8.setBackground(new java.awt.Color(102, 255, 204));
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField8.setBorder(null);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));

        CostosFin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CostosFin.setBorder(null);
        CostosFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostosFinActionPerformed(evt);
            }
        });
        jPanel3.add(CostosFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        jTextField10.setBackground(new java.awt.Color(102, 255, 204));
        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        jTextField13.setBackground(new java.awt.Color(102, 255, 204));
        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField13.setBorder(null);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 120, 30));

        GastosVentas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GastosVentas.setBorder(null);
        GastosVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastosVentasActionPerformed(evt);
            }
        });
        jPanel3.add(GastosVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 120, 30));

        GAstosdeAdministracion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GAstosdeAdministracion.setBorder(null);
        GAstosdeAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAstosdeAdministracionActionPerformed(evt);
            }
        });
        jPanel3.add(GAstosdeAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 120, 30));

        OtrosGastos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OtrosGastos.setBorder(null);
        OtrosGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtrosGastosActionPerformed(evt);
            }
        });
        jPanel3.add(OtrosGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 30));

        jTextField18.setBackground(new java.awt.Color(102, 255, 204));
        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField18.setBorder(null);
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        CostosMer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CostosMer.setBorder(null);
        CostosMer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostosMerActionPerformed(evt);
            }
        });
        jPanel3.add(CostosMer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 30));

        TotalIngresos2.setBackground(new java.awt.Color(102, 255, 204));
        TotalIngresos2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TotalIngresos2.setBorder(null);
        TotalIngresos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalIngresos2ActionPerformed(evt);
            }
        });
        jPanel3.add(TotalIngresos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 150, 600));

        jPanel5.setBackground(new java.awt.Color(102, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 220, 190, 40));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 40, 240, 40));

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 70, 240, 40));

        jSeparator20.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 100, 240, 40));

        jSeparator21.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 130, 200, 40));

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 160, 240, 40));

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 490, 180, 40));

        jSeparator44.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 190, 240, 40));

        jSeparator45.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 250, 200, 40));

        jSeparator46.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 280, 240, 40));

        jSeparator47.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 310, 200, 40));

        jSeparator48.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 340, 240, 40));

        jSeparator49.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 370, 240, 40));

        jSeparator50.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 240, 40));

        jSeparator51.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 430, 240, 40));

        jSeparator52.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator52, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 460, 240, 40));

        jSeparator61.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 160, 40));

        jSeparator62.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 160, 40));

        jSeparator63.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, 40));

        TotalIngresos1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TotalIngresos1.setBorder(null);
        TotalIngresos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalIngresos1ActionPerformed(evt);
            }
        });
        jPanel5.add(TotalIngresos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        UtilidadBruta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UtilidadBruta.setBorder(null);
        UtilidadBruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilidadBrutaActionPerformed(evt);
            }
        });
        jPanel5.add(UtilidadBruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, 30));

        TotalCostos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TotalCostos.setBorder(null);
        TotalCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalCostosActionPerformed(evt);
            }
        });
        jPanel5.add(TotalCostos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 30));

        TotalGastos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TotalGastos.setBorder(null);
        TotalGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalGastosActionPerformed(evt);
            }
        });
        jPanel5.add(TotalGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 120, 30));

        UtilidadesdelPeriodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UtilidadesdelPeriodo.setBorder(null);
        UtilidadesdelPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilidadesdelPeriodoActionPerformed(evt);
            }
        });
        jPanel5.add(UtilidadesdelPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 120, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, 600));

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jButton2.setText("GENERAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jButton3.setText("GENERAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jButton4.setText("GENERAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jButton5.setText("GENERAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel7.setText("PERSONA QUE AUTORISA");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 170, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 160, 30));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 30));

        jLabel22.setText("NOMBRE QUIEN ELABORO");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 170, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 330, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void UtilidadesdelPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilidadesdelPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UtilidadesdelPeriodoActionPerformed

    private void VentasMerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasMerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentasMerActionPerformed

    private void IngresosFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresosFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresosFinActionPerformed

    private void TotalCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalCostosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalCostosActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void CostosFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostosFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostosFinActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void UtilidadBrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilidadBrutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UtilidadBrutaActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void GastosVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastosVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GastosVentasActionPerformed

    private void GAstosdeAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAstosdeAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GAstosdeAdministracionActionPerformed

    private void OtrosGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtrosGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtrosGastosActionPerformed

    private void TotalGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalGastosActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void TotalIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalIngresos1ActionPerformed

    private void CostosMerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostosMerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostosMerActionPerformed

    private void TotalIngresos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalIngresos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalIngresos2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double vm = new Double(VentasMer.getText()); 
        Double If = new Double(IngresosFin.getText());
        Double CM = new Double(CostosMer.getText()); 
        Double CF = new Double(CostosFin.getText());
        
        Double TotalIngresos = vm + If;
        Double TotalCosto = CM + CF;
        Double UB = TotalIngresos - TotalCosto;
        
        Double GV = new Double(GastosVentas.getText()); 
        Double GA = new Double(GAstosdeAdministracion.getText());
        Double OG = new Double(OtrosGastos.getText());
        
        Double TOLGAS = GV + GA + OG;
        
        Double Utilidades = UB - TOLGAS;
        
        UtilidadesdelPeriodo.setText(""+(Utilidades));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Double vm = new Double(VentasMer.getText()); 
        Double If = new Double(IngresosFin.getText());
        
        Double TotalIngresos = vm + If;
        
        TotalIngresos1.setText(""+(TotalIngresos));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Double CM = new Double(CostosMer.getText()); 
        Double CF = new Double(CostosFin.getText());
        
        Double TotalCosto = CM + CF;
        
        TotalCostos.setText(""+(TotalCosto));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        Double vm = new Double(VentasMer.getText()); 
        Double If = new Double(IngresosFin.getText());
        Double CM = new Double(CostosMer.getText()); 
        Double CF = new Double(CostosFin.getText());
        
        Double TotalIngresos = vm + If;
        Double TotalCosto = CM + CF;
        Double UB = TotalIngresos - TotalCosto;
        
        UtilidadBruta.setText(""+(UB));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Double GV = new Double(GastosVentas.getText()); 
        Double GA = new Double(GAstosdeAdministracion.getText());
        Double OG = new Double(OtrosGastos.getText());
        
        Double TOLGAS = GV + GA + OG;
        
        TotalGastos.setText(""+(TOLGAS));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CostosFin;
    private javax.swing.JTextField CostosMer;
    private javax.swing.JTextField GAstosdeAdministracion;
    private javax.swing.JTextField GastosVentas;
    private javax.swing.JTextField IngresosFin;
    private javax.swing.JTextField OtrosGastos;
    private javax.swing.JTextField TotalCostos;
    private javax.swing.JTextField TotalGastos;
    private javax.swing.JTextField TotalIngresos1;
    private javax.swing.JTextField TotalIngresos2;
    private javax.swing.JTextField UtilidadBruta;
    private javax.swing.JTextField UtilidadesdelPeriodo;
    private javax.swing.JTextField VentasMer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
